// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivjicmtmmuimpqrhtcgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2amljbXRtbXVpbXBxcmh0Y2d0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1OTczNDksImV4cCI6MjA2OTE3MzM0OX0.b0P3JzQSOpGlf4aMPjcM0o3aYK1_Nm1nE560Rcvw4jw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});